### ISSUE TITLE
[1.18.2 6.1] Game crashes after applying changes

### ISSUE THREAD

**Issue by DSRoie** [TheComputerizer/Music-Triggers#109]
**Describe the bug**
Game crashes after applying changes

**Additional context**
[15:16:27] [Render thread/ERROR]: SOUND CATEGORY IS MUSIC
[15:16:27] [LavaPlayer Audio Thread/ERROR]: Uncaught exception in thread "LavaPlayer Audio Thread"
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:942) [?:?]
	at mods.thecomputerizer.musictriggers.client.audio.ChannelListener.stop(ChannelListener.java:40) ~[Music-Triggers-1.18.2-fabric-6.1.jar:?]
	at mods.thecomputerizer.musictriggers.client.audio.Channel.clear(Channel.java:878) ~[Music-Triggers-1.18.2-fabric-6.1.jar:?]
	at mods.thecomputerizer.musictriggers.client.audio.ChannelManager.reloadAllChannels(ChannelManager.java:176) ~[Music-Triggers-1.18.2-fabric-6.1.jar:?]
	at mods.thecomputerizer.musictriggers.client.ClientEvents.onTick(ClientEvents.java:104) ~[Music-Triggers-1.18.2-fabric-6.1.jar:?]
	at mods.thecomputerizer.musictriggers.MusicTriggersClient.lambda$setUpClientEvents$4(MusicTriggersClient.java:76) ~[Music-Triggers-1.18.2-fabric-6.1.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65) ~[fabric-lifecycle-events-v1-2.1.1+cc71601c60-475b431be44cb7c1.jar:?]
	at net.minecraft.class_310.handler$dac000$onEndTick(class_310.java:15479) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1817) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1091) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) ~[1.18.2-Fabric%200.14.14.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.14.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
[15:16:27] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Invalid table definition on line 7: [songs.example]]
	at com.moandjiezana.toml.Toml.read(Toml.java:140) ~[com_moandjiezana_toml_toml4j-0.7.2-ca135c402bcc6609.jar:?]
	at com.moandjiezana.toml.Toml.read(Toml.java:107) ~[com_moandjiezana_toml_toml4j-0.7.2-ca135c402bcc6609.jar:?]
	at com.moandjiezana.toml.Toml.read(Toml.java:86) ~[com_moandjiezana_toml_toml4j-0.7.2-ca135c402bcc6609.jar:?]
	at mods.thecomputerizer.theimpossiblelibrary.util.file.TomlUtil.get(TomlUtil.java:24) ~[theimpossiblelibrary-1.18.2-fabric-0.2.4.jar:?]
	at mods.thecomputerizer.theimpossiblelibrary.common.toml.Holder.<init>(Holder.java:55) ~[theimpossiblelibrary-1.18.2-fabric-0.2.4.jar:?]
	at mods.thecomputerizer.theimpossiblelibrary.common.toml.Holder.<init>(Holder.java:45) ~[theimpossiblelibrary-1.18.2-fabric-0.2.4.jar:?]
	at mods.thecomputerizer.theimpossiblelibrary.util.file.TomlUtil.readFully(TomlUtil.java:469) ~[theimpossiblelibrary-1.18.2-fabric-0.2.4.jar:?]
	at mods.thecomputerizer.musictriggers.client.audio.Channel.<init>(Channel.java:118) ~[Music-Triggers-1.18.2-fabric-6.1.jar:?]
	at mods.thecomputerizer.musictriggers.client.audio.ChannelManager.initialize(ChannelManager.java:62) ~[Music-Triggers-1.18.2-fabric-6.1.jar:?]
	at mods.thecomputerizer.musictriggers.client.audio.ChannelManager.reloadAllChannels(ChannelManager.java:179) ~[Music-Triggers-1.18.2-fabric-6.1.jar:?]
	at mods.thecomputerizer.musictriggers.client.ClientEvents.onTick(ClientEvents.java:104) ~[Music-Triggers-1.18.2-fabric-6.1.jar:?]
	at mods.thecomputerizer.musictriggers.MusicTriggersClient.lambda$setUpClientEvents$4(MusicTriggersClient.java:76) ~[Music-Triggers-1.18.2-fabric-6.1.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65) ~[fabric-lifecycle-events-v1-2.1.1+cc71601c60-475b431be44cb7c1.jar:?]
	at net.minecraft.class_310.handler$dac000$onEndTick(class_310.java:15479) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1817) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1091) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.14.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]

**Comment by TheComputerizer** [comment]
Song names cant have spaces in them, this is not an issue with the mod
