### ISSUE TITLE
1.19.2 game won't start

### ISSUE THREAD

**Issue by ink717** [TheComputerizer/Music-Triggers#154]
the game simply won't start, no crash log generated. repeated error:
regardless of whether disabling other mods or changing forge version

[27/11/2023 08:46:39 AM] Exception in thread "main" java.lang.module.ResolutionException: Modules musictriggers and worldedit export package org.mozilla.javascript.xmlimpl to module worldedit (note: the mod in this column changes each time!)
[27/11/2023 08:46:39 AM] 	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
[27/11/2023 08:46:39 AM] 	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
[27/11/2023 08:46:39 AM] 	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
[27/11/2023 08:46:39 AM] 	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
[27/11/2023 08:46:39 AM] 	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
[27/11/2023 08:46:39 AM] 	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
[27/11/2023 08:46:39 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
[27/11/2023 08:46:39 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
[27/11/2023 08:46:39 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
[27/11/2023 08:46:39 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
[27/11/2023 08:46:39 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[27/11/2023 08:46:39 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[27/11/2023 08:46:39 AM] 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[27/11/2023 08:46:39 AM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.

**Comment by TheComputerizer** [comment]
There isn't enough information to go on here, but just to take a guess, do you have WorldEdit installed as well?

**Comment by Darkstar6423** [comment]
I had a similar issue and after removing world edit I was able to run the game. The only difference was that modrinth was reporting an I/O issue and it wasn't in the game logs (latest.txt)

**Comment by TheComputerizer** [comment]
#155 is a duplicate but I'll close this one since I put better information there
