### ISSUE TITLE
[Crash Report] [1.18.2 Fabric v5.2] Game crashes when using Wiki example.

### ISSUE THREAD

**Issue by Danuge** [TheComputerizer/Music-Triggers#25]
I'm trying to learn the mod because it seems really cool, so I tried adding the [example found on the wiki](https://github.com/TheComputerizer/Music-Triggers/wiki/A-Complex-Example), just changing the timing of the loops and the name of the song, but when I try to load up a world the game crashes and I get this message

```
java.lang.RuntimeException: There was a problem with your victory trigger! The error was Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.HashMap.get(Object)" is null and was caught on line 912 of the class mods.thecomputerizer.musictriggers.client.MusicPicker.playableEvents(MusicPicker.java:912)
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.63)
	at mods.thecomputerizer.musictriggers.client.MusicPicker.playableEvents(MusicPicker.java:1140)
	at mods.thecomputerizer.musictriggers.client.MusicPicker.playThese(MusicPicker.java:86)
	at mods.thecomputerizer.musictriggers.client.MusicPlayer.onTick(MusicPlayer.java:302)
	at mods.thecomputerizer.musictriggers.MusicTriggersClient.lambda$setUpClientEvents$2(MusicTriggersClient.java:99)
	at org.quiltmc.qsl.lifecycle.api.client.event.ClientTickEvents.lambda$static$2(ClientTickEvents.java:54)
	at net.minecraft.client.MinecraftClient.handler$cpo001$endTick(MinecraftClient:21004)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1817)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

(yes I have NEC, also I tried deleting every mod except fabric API and MusicTriggers but to no avail)
I even tried just copying the raw example to my musictriggers.toml file without making any changes whatsoever and it still crashes.

**Comment by TheComputerizer** [comment]
It was an issue with the victory trigger. Fixed in 5.3
