### ISSUE TITLE
[1.18.2-fabric-5.3] Error when starting server 

### ISSUE THREAD

**Issue by kusayu** [TheComputerizer/Music-Triggers#32]
I'm sorry but I found another error when starting the server with the mod
server-loader: fabric 0.14.4
mc version: 1.18.2

```
[20:10:17] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'musictriggers'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.4.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:67) [fabric-loader-0.14.4.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1109
	at mods.thecomputerizer.musictriggers.common.ModSounds.init(ModSounds.java:29) ~[Music-Triggers-1.18.2-fabric-5.3.jar:?]
	at mods.thecomputerizer.musictriggers.util.RegistryHandler.registerSoundEvents(RegistryHandler.java:20) ~[Music-Triggers-1.18.2-fabric-5.3.jar:?]
	at mods.thecomputerizer.musictriggers.util.RegistryHandler.init(RegistryHandler.java:34) ~[Music-Triggers-1.18.2-fabric-5.3.jar:?]
	at mods.thecomputerizer.musictriggers.MusicTriggersCommon.onInitialize(MusicTriggersCommon.java:66) ~[Music-Triggers-1.18.2-fabric-5.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.4.jar:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: can't find class net.minecraft.class_1109
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:227) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at mods.thecomputerizer.musictriggers.common.ModSounds.init(ModSounds.java:29) ~[Music-Triggers-1.18.2-fabric-5.3.jar:?]
	at mods.thecomputerizer.musictriggers.util.RegistryHandler.registerSoundEvents(RegistryHandler.java:20) ~[Music-Triggers-1.18.2-fabric-5.3.jar:?]
	at mods.thecomputerizer.musictriggers.util.RegistryHandler.init(RegistryHandler.java:34) ~[Music-Triggers-1.18.2-fabric-5.3.jar:?]
	at mods.thecomputerizer.musictriggers.MusicTriggersCommon.onInitialize(MusicTriggersCommon.java:66) ~[Music-Triggers-1.18.2-fabric-5.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.4.jar:?]
	... 15 more
```

Full Log:
[latest.log](https://github.com/TheComputerizer/Music-Triggers/files/8645868/latest.log)

**Comment by TheComputerizer** [comment]
Yeah my bad I missed a client class on the server side. I should probably test and make sure it works next time
