### ISSUE TITLE
Issue on 1.12.2

### ISSUE THREAD

**Issue by salzstreuerimkorallenriff** [TheComputerizer/Music-Triggers#5]
Hello there,
I've tried your mod and after adding some songs minecraft crashed and now it don't start properly. Can you help me please?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 11/27/21 1:35 AM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 1
	at mods.thecomputerizer.musictriggers.common.SoundHandler.registerSounds(SoundHandler.java:950)
	at mods.thecomputerizer.musictriggers.common.MusicTriggersItems.init(MusicTriggersItems.java:26)
	at mods.thecomputerizer.musictriggers.util.RegistryHandler.onRegisterItems(RegistryHandler.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_RegistryHandler_onRegisterItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mods.thecomputerizer.musictriggers.common.SoundHandler.registerSounds(SoundHandler.java:950)
	at mods.thecomputerizer.musictriggers.common.MusicTriggersItems.init(MusicTriggersItems.java:26)
	at mods.thecomputerizer.musictriggers.util.RegistryHandler.onRegisterItems(RegistryHandler.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_RegistryHandler_onRegisterItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 781606616 bytes (745 MB) / 1006632960 bytes (960 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version      | Source                        | Signature                                |
	|:----- |:------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCH   | minecraft     | 1.12.2       | minecraft.jar                 | None                                     |
	| LCH   | mcp           | 9.42         | minecraft.jar                 | None                                     |
	| LCH   | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge         | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | bloodmoon     | 1.5.3        | Bloodmoon-MC1.12.2-1.5.3.jar  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | musictriggers | 3.3          | music-triggers-3.5.jar        | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 472.12' Renderer: 'NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2'
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz

**Comment by TheComputerizer** [comment]
It looks like you may have an error in your config, can you send that

**Comment by salzstreuerimkorallenriff** [comment]
[musictriggers(config).txt](https://github.com/TheComputerizer/Music-Triggers/files/7610985/musictriggers.config.txt)

**Comment by TheComputerizer** [comment]
Your night and mob triggers are configured incorrectly, there are examples of the correct formatting you can find in that file

**Comment by salzstreuerimkorallenriff** [comment]
My bad! I'll try it again! Tanks!
